### ISSUE TITLE
[Vulnerability Upgrade] Use node-forge@0.10.0 

### ISSUE THREAD

**Issue by solidprinciples** [digitalbazaar/rdf-canonize#30]
Fixes a low risk CVE outlined here:
https://nvd.nist.gov/vuln/detail/CVE-2020-7720

Maybe a minor version bump to 1.1.1 - to allow for ^1.*.* dependencies to work without upgrading?

**Comment by davidemontanari** [comment]
Checking the PR page, dependabot already tried to upgrade the dependency without success: https://github.com/digitalbazaar/rdf-canonize/pull/29. Since the severity is high/critical, @davidlehn are there any ETAs for fixing this? Thank you!

**Comment by dlongley** [comment]
Not sure what the ETA on a fix is, but I wanted to assure everyone that the severity is not actually high/critical (despite the report). The affected code is in a deprecated utility library within node-forge that this library does not use.

For those interested, the vulnerability in this case is really a complaint about a legitimate feature for setting a value in an object using a dot-delimited path. The vulnerability report suggests that using `__proto__` in the path should not be permitted -- but this is not a vulnerability, it is a choice. If there are certain paths that an application finds undesirable, then it should not use them nor permit them as user input, but this is clearly a decision for the application developer, not the library developer. A function that takes a pointer to some memory and a length for the allocated space as parameters is not *broken* just because a bad application may allow an incorrect length to be passed in.

Regardless, we will still address the issue as soon as we have cycles... because vulnerability reports look scary -- even when they aren't. People don't have the time to look into every one to make their own decisions and, unfortunately, sometimes things like this happen and create churn.

**Comment by mattcollier** [comment]
Addressed in https://github.com/digitalbazaar/rdf-canonize/commit/2afe03a8e8a174ee13ff9b785a12def7ed30e7bf
